import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Architecture, BIM, Revit & 3D Rendering Guides | Artimist",
  description: "Practical guides on house plans, permit drawings, BIM, Revit, CAD, architectural rendering and visualization for homeowners and professional teams.",
  alternates: { canonical: "/insights" },
  openGraph: { title: "Architecture, BIM, Revit & 3D Rendering Guides | Artimist", description: "Practical architecture, BIM, drafting and visualization guidance from Artimist Productions.", url: "https://www.artimistproductions.com/insights", type: "website" },
};

const articles = [
  ["how-much-do-custom-house-plans-cost", "How much do custom house plans cost?", "What changes the price of custom residential design and what homeowners should compare before requesting a quote.", "/media/generated-architecture/artimist-architecture-029.webp", "Compact courtyard house floor plans"],
  ["permit-drawings-vs-construction-drawings", "Permit drawings vs construction drawings", "The difference in purpose, detail and project use between approval sets and construction information.", "/media/generated-architecture/artimist-architecture-012.webp", "Residential permit drawing set"],
  ["how-to-modify-an-existing-floor-plan", "How to modify an existing floor plan", "A practical way to improve circulation, room sizes and adjacencies without losing control of the existing structure.", "/media/generated-architecture/artimist-architecture-053.webp", "Existing and proposed apartment plans"],
  ["revit-drafting-vs-cad-drafting", "Revit drafting vs CAD drafting", "When BIM adds value, when 2D CAD is enough and how to choose the right production workflow.", "/media/generated-architecture/artimist-architecture-043.webp", "Coordinated townhouse floor plans"],
  ["what-is-scan-to-bim", "What is Scan-to-BIM?", "How point-cloud information becomes a usable BIM model and what clients need to provide before modeling begins.", "/media/generated-architecture/artimist-architecture-088.webp", "Measured townhouse section"],
  ["lod-200-vs-lod-300-vs-lod-400", "LOD 200 vs LOD 300 vs LOD 400", "A plain-language explanation of BIM development levels and why the required LOD should be defined before production.", "/media/generated-architecture/artimist-architecture-054.webp", "Exploded architectural assembly"],
  ["how-much-does-architectural-rendering-cost", "How much does architectural rendering cost?", "The main variables behind rendering fees: model readiness, image count, complexity, revisions, resolution and animation.", "/media/generated-architecture/artimist-architecture-035.webp", "Rendered courtyard house study"],
  ["3d-rendering-vs-unreal-engine-walkthrough", "3D rendering vs Unreal Engine walkthrough", "How still CGI, animation and real-time walkthroughs differ in cost, flexibility and presentation value.", "/media/editorial/kinetic-roof-technical.webp", "Real-time architectural environment study"],
  ["do-house-plans-need-an-architect-stamp", "Do house plans need an architect's stamp?", "Why the answer changes by state, jurisdiction, building type and project scope—and what to confirm before ordering drawings.", "/img/permit01.webp", "Residential permit drawing sheet"],
  ["what-drawings-are-needed-for-a-home-addition-permit", "What drawings are needed for a home addition permit?", "A plain-language checklist for U.S. homeowners, with the important reminder that every permitting authority sets its own requirements.", "/img/permit04.webp", "Home addition permit drawing package"],
  ["how-to-turn-a-hand-sketch-into-floor-plans", "How to turn a hand sketch into floor plans", "What dimensions, photos and project notes help convert a rough idea into an accurate, useful architectural floor plan.", "/media/technical/board-16.webp", "Hand sketch developed into architectural drawings"],
  ["what-to-send-for-a-3d-home-rendering", "What to send for a 3D home rendering", "The plans, references and decisions a visualization studio needs to quote accurately and produce useful images.", "/img/resext03.webp", "Photoreal house exterior rendering"],
] as const;

const CSS = `.ins{min-height:100vh;background:#090809;color:#eee8e3;padding:116px 0 120px;font-family:Arial,Helvetica,sans-serif}.ins *{box-sizing:border-box}.ins a{color:inherit}.ins-wrap{width:min(1280px,calc(100% - 40px));margin:auto}.ins-hero{min-height:calc(100vh - 160px);display:grid;grid-template-columns:.72fr 1.28fr;gap:clamp(34px,6vw,86px);align-items:center;margin-bottom:70px;border-bottom:1px solid rgba(255,255,255,.12)}.ins-hero-visual{margin:0;position:relative;overflow:hidden;border:1px solid rgba(255,255,255,.1);aspect-ratio:4/3;background:#eee7dd}.ins-hero-visual img{width:100%;height:100%;object-fit:cover;display:block}.ins-hero-visual figcaption{position:absolute;left:16px;bottom:16px;background:rgba(9,8,9,.82);padding:8px 11px;font-size:9px;letter-spacing:.14em;text-transform:uppercase}.ins-kicker{font-size:11px;letter-spacing:.2em;text-transform:uppercase;color:#d45e73;font-weight:700}.ins h1,.ins h2{font-family:Georgia,'Times New Roman',serif;font-weight:400}.ins h1{font-size:clamp(54px,7.2vw,100px);line-height:.84;letter-spacing:-.045em;margin:16px 0 22px}.ins-lead{max-width:70ch;color:#b9aea8;font-size:19px;line-height:1.65;margin:0}.ins-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:0;border-top:1px solid rgba(255,255,255,.14)}.ins-card{grid-column:span 6;display:grid;grid-template-columns:210px 1fr;text-decoration:none;border:1px solid rgba(255,255,255,.1);background:#100e0f;min-height:250px;overflow:hidden;transition:transform .25s ease,border-color .25s ease}.ins-card:hover{transform:translateY(-2px);border-color:rgba(212,94,115,.48)}.ins-card-visual{margin:0;background:#e9e2d8;overflow:hidden}.ins-card-visual img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .5s ease}.ins-card:hover img{transform:scale(1.025)}.ins-card-copy{padding:28px;border-left:1px solid rgba(255,255,255,.1)}.ins-card small{color:#d45e73;letter-spacing:.14em;text-transform:uppercase}.ins-card h2{font-size:28px;line-height:1.08;margin:16px 0 12px}.ins-card p{margin:0;color:#a99e98;line-height:1.55;font-size:14px}.ins-actions{margin-top:46px;display:flex;gap:10px;flex-wrap:wrap}.ins-actions a{border:1px solid rgba(255,255,255,.12);padding:10px 15px;text-decoration:none;color:#c9beb8}@media(max-width:900px){.ins-hero{min-height:auto;grid-template-columns:1fr;gap:34px;padding:46px 0 60px}.ins-grid{grid-template-columns:1fr}.ins-card{grid-column:auto}}@media(max-width:600px){.ins{padding-top:92px}.ins-wrap{width:min(100% - 28px,1200px)}.ins-hero{margin-bottom:42px}.ins-card{grid-template-columns:1fr;min-height:0}.ins-card-visual{aspect-ratio:16/9}.ins-card-copy{padding:22px}.ins h1{font-size:clamp(48px,14vw,66px)}}`;

export default function InsightsPage() {
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: "Artimist Architecture, BIM and Visualization Guides", url: "https://www.artimistproductions.com/insights", isPartOf: { "@id": "https://www.artimistproductions.com/#website" } };
  return <main className="ins"><style dangerouslySetInnerHTML={{ __html: CSS }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="ins-wrap"><section className="ins-hero"><div><div className="ins-kicker">Knowledge / practical project guidance</div><h1>Clear guidance before the project starts.</h1><p className="ins-lead">Clear explanations for homeowners, architects, developers and production teams comparing design, drafting, BIM and visualization scopes. These guides are written to help define the right brief rather than inflate the service.</p></div><figure className="ins-hero-visual"><img src="/media/generated-architecture/artimist-architecture-030.webp" alt="Architectural section through a compact courtyard house" width="1600" height="900" fetchPriority="high" /><figcaption>Plans, sections and decisions / Artimist</figcaption></figure></section><div className="ins-grid">{articles.map(([slug,title,copy,image,alt],i)=><Link className="ins-card" key={slug} href={`/insights/${slug}`}><figure className="ins-card-visual"><img src={image} alt={alt} width="800" height="600" loading="lazy" decoding="async" /></figure><div className="ins-card-copy"><small>Guide {String(i+1).padStart(2,"0")}</small><h2>{title}</h2><p>{copy}</p></div></Link>)}</div><div className="ins-actions"><Link href="/services">Explore services</Link><Link href="/case-studies">View case studies</Link><Link href="/international">International delivery</Link><Link href="/contact">Start a project brief</Link></div></div></main>;
}
