import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Home Design Services, Floor Plans, Interiors & 3D | Artimist",
  description: "Home design help in simple terms: custom house plans, floor plan changes, interior design, renovation drawings, 3D visualization and drafting for homeowners worldwide.",
  alternates: { canonical: "/home-design-services" },
};

const services = [
  { title: "Design my house", text: "Custom house plans, new-home layouts and residential design developed around your site and the way you want to live.", href: "/custom-house-design", image: "/img/resext03.webp", alt: "Contemporary residential design project by Artimist Productions" },
  { title: "Design my interior", text: "Living rooms, kitchens, bedrooms, bathrooms and whole-home interiors with realistic 3D views before you build.", href: "/3d-interior-design-service", image: "/img/homeint03.webp", alt: "Photoreal interior design project by Artimist Productions" },
  { title: "Change my floor plan", text: "Already have a plan? We can redraw it, improve the layout, move rooms, add spaces and show the new version clearly.", href: "/plan-modification-service", image: "/img/permit04.webp", alt: "Residential drawing sheet showing coordinated design work" },
  { title: "Plan my renovation", text: "Drawings for remodels, additions, extensions, basement projects, garage conversions, kitchens and bathrooms.", href: "/residential-renovation-permit-drawings", image: "/media/projects/permit-sets.webp", alt: "Residential permit documentation set by Artimist Productions" },
  { title: "Show me what it will look like", text: "Photoreal 3D rendering and architectural visualization so you can judge design, materials and light before construction.", href: "/visualization", image: "/img/resid01.webp", alt: "Photoreal residential architecture visualization" },
  { title: "Prepare clean drawings", text: "Floor plans, elevations, sections, CAD and Revit drafting when you need clear, usable project drawings.", href: "/architectural-drafting-services", image: "/img/permit01.webp", alt: "Architectural drafting and permit drawing package" },
];

const css = `
.hdh{background:#090909;color:#f2ece7;min-height:100vh;font-family:Arial,Helvetica,sans-serif;overflow:hidden}.hdh *{box-sizing:border-box}.hdh a{color:inherit;text-decoration:none}.hdh-wrap{width:min(1240px,calc(100% - 40px));margin:auto;padding:138px 0 130px}.hdh-intro{position:relative;z-index:1;max-width:980px;padding-bottom:56px}.hdh-intro:after{content:'';position:absolute;z-index:-1;width:420px;height:420px;left:-190px;top:-170px;border-radius:50%;background:rgba(156,31,53,.13);filter:blur(95px)}.hdh-eyebrow{color:#c95469;font-size:11px;font-weight:700;letter-spacing:.2em;text-transform:uppercase}.hdh h1,.hdh h2,.hdh h3{font-family:Georgia,'Times New Roman',serif;font-weight:400}.hdh h1{font-size:clamp(48px,7vw,92px);line-height:.98;letter-spacing:-.045em;max-width:12ch;margin:16px 0 22px}.hdh-lead{max-width:730px;color:#b7ada7;font-size:19px;line-height:1.6;margin:0}.hdh-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.hdh-card{position:relative;min-height:520px;overflow:hidden;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:#121011;isolation:isolate}.hdh-card img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;transition:transform 1.25s cubic-bezier(.2,.8,.2,1);animation:hdhFloat 14s ease-in-out infinite alternate}.hdh-card:after{content:'';position:absolute;inset:0;background:linear-gradient(0deg,rgba(5,5,5,.95) 0%,rgba(5,5,5,.55) 42%,rgba(5,5,5,.06) 78%)}.hdh-card article{position:absolute;z-index:2;left:28px;right:28px;bottom:27px}.hdh-card small{color:#d86a7b;font-size:10px;letter-spacing:.16em;text-transform:uppercase}.hdh-card h2{font-size:38px;line-height:1.05;margin:9px 0 10px}.hdh-card p{max-width:55ch;margin:0;color:#c1b7b1;font-size:14px;line-height:1.55}.hdh-card:hover img{transform:scale(1.045)}.hdh-bottom{margin-top:54px;padding:42px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:linear-gradient(135deg,rgba(156,31,53,.18),rgba(255,255,255,.02));display:flex;justify-content:space-between;gap:30px;align-items:center}.hdh-bottom h3{font-size:34px;margin:0 0 6px}.hdh-bottom p{margin:0;color:#aaa09a}.hdh-btn{display:inline-flex;padding:14px 20px;border-radius:999px;background:#9c1f35;font-size:12px;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}@keyframes hdhFloat{from{transform:scale(1.01) translateY(0)}to{transform:scale(1.045) translateY(-6px)}}
@media(max-width:760px){.hdh-wrap{width:100%;padding:118px 0 150px}.hdh-intro{padding:0 22px 38px}.hdh-eyebrow{font-size:9px}.hdh h1{font-size:clamp(43px,13.2vw,64px);line-height:.94;max-width:8.8ch;margin-top:13px}.hdh-lead{font-size:16px;line-height:1.55;max-width:34ch}.hdh-grid{display:flex;gap:12px;overflow-x:auto;scroll-snap-type:x mandatory;padding:0 22px 8px;scrollbar-width:none;-webkit-overflow-scrolling:touch}.hdh-grid::-webkit-scrollbar{display:none}.hdh-card{flex:0 0 min(82vw,430px);min-height:112vw;max-height:570px;border-radius:10px;scroll-snap-align:center}.hdh-card article{left:20px;right:20px;bottom:22px}.hdh-card h2{font-size:34px}.hdh-card p{font-size:14px}.hdh-bottom{margin:42px 22px 0;display:block;padding:28px;border-radius:12px}.hdh-bottom h3{font-size:30px}.hdh-btn{margin-top:22px}.hdh-card:nth-child(even) img{animation-direction:alternate-reverse}}
@media(prefers-reduced-motion:reduce){.hdh-card img{animation:none}}
`;

export default function HomeDesignServicesPage() {
  return <main className="hdh"><style dangerouslySetInnerHTML={{__html:css}}/><div className="hdh-wrap"><header className="hdh-intro"><div className="hdh-eyebrow">Homeowners / start with the problem</div><h1>What do you need help with?</h1><p className="hdh-lead">You do not need to know architectural terminology. Choose what you are trying to change, design or visualize and we will guide you to the right next step.</p></header><section className="hdh-grid" aria-label="Home design services">{services.map((s,i)=><Link className="hdh-card" href={s.href} key={s.href}><img src={s.image} alt={s.alt} loading={i<2?"eager":"lazy"}/><article><small>{String(i+1).padStart(2,"0")} / Common request</small><h2>{s.title}</h2><p>{s.text}</p></article></Link>)}</section><section className="hdh-bottom"><div><h3>Not sure what the service is called?</h3><p>Send the plan, photo, sketch or idea you already have. We can tell you the most useful next step.</p></div><a className="hdh-btn" href="https://wa.me/18078084181" target="_blank" rel="noreferrer">Talk to the studio on WhatsApp</a></section></div></main>;
}
